/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.HewanPeliharaan;
import Models.Kucing;
import java.awt.event.ActionListener;

/**
 *
 * @author Farrel
 */
public class ViewInvoice extends javax.swing.JFrame {

    /**
     * Creates new form ViewInvoice
     */
    public ViewInvoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldNamaPemilik = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldNamaHewan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldJenisHewan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldBiayaLayanan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldLayanan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        fieldMetodePembayaran = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldNoInvoice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldDiskon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldTotalBiaya = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PEMBAYARAN BERHASIL!!!");

        jLabel3.setText("Nama Pemilik : ");

        fieldNamaPemilik.setEditable(false);
        fieldNamaPemilik.setText("Nama Pemilik");

        jLabel2.setText("Nama Hewan : ");

        fieldNamaHewan.setEditable(false);
        fieldNamaHewan.setText("Nama Hewan");

        jLabel8.setText("Jenis Hewan : ");

        fieldJenisHewan.setEditable(false);
        fieldJenisHewan.setText("Jenis Hewan");

        jLabel4.setText("Biaya Layanan :");

        fieldBiayaLayanan.setEditable(false);
        fieldBiayaLayanan.setText("Biaya Layanan");

        jLabel6.setText("Jenis Layanan :");

        fieldLayanan.setEditable(false);
        fieldLayanan.setText("Layanan");
        fieldLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLayananActionPerformed(evt);
            }
        });

        jLabel5.setText("Metode Pembayaran :");

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        fieldMetodePembayaran.setEditable(false);
        fieldMetodePembayaran.setText("Metode Pembayaran");
        fieldMetodePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMetodePembayaranActionPerformed(evt);
            }
        });

        jLabel7.setText("No. Invoice:");

        fieldNoInvoice.setEditable(false);
        fieldNoInvoice.setText("No. Invoice");

        jLabel9.setText("Diskon :");

        fieldDiskon.setEditable(false);
        fieldDiskon.setText("Diskon");

        jLabel10.setText("Total Biaya :");

        fieldTotalBiaya.setEditable(false);
        fieldTotalBiaya.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        fieldTotalBiaya.setText("Total Biaya");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9)
                                .addComponent(fieldJenisHewan)
                                .addComponent(jLabel8)
                                .addComponent(fieldNamaHewan)
                                .addComponent(jLabel2)
                                .addComponent(fieldNamaPemilik)
                                .addComponent(jLabel3)
                                .addComponent(fieldNoInvoice)
                                .addComponent(jLabel7)
                                .addComponent(fieldLayanan)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(fieldMetodePembayaran)
                                .addComponent(fieldBiayaLayanan)
                                .addComponent(fieldDiskon)
                                .addComponent(fieldTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(btnSelesai)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNoInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNamaPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNamaHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldJenisHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldBiayaLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSelesai)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void fieldLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLayananActionPerformed

    private void fieldMetodePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMetodePembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMetodePembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ViewInvoice().setVisible(true);
            }
        });
    }
    
    public void setNoInvoice(String noInvoice){
        fieldNoInvoice.setText(noInvoice);
    }
    
    public void setNamaPemilik(String nama) {
        fieldNamaPemilik.setText(nama);
    }
    
    public void setNamaHewan(String namaHewan) {
        fieldNamaHewan.setText(namaHewan);
    }
    
    public void setJenisHewan(HewanPeliharaan hewanPeliharaan) {
        String jenisHewan = "";
        
        if (hewanPeliharaan instanceof Kucing) {
            jenisHewan = "Kucing";
        } else {
            jenisHewan = "Anjing";
        }
        
        fieldJenisHewan.setText(jenisHewan);
    }
        
    public void setLayanan(String layanan) {
        fieldLayanan.setText(layanan);
    }
    
    public void setMetodePembayaran(String metodePembayaran){
        fieldMetodePembayaran.setText(metodePembayaran);
    }
    
    public void addActionSelesai(ActionListener listener) {
        btnSelesai.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelesai;
    private javax.swing.JTextField fieldBiayaLayanan;
    private javax.swing.JTextField fieldDiskon;
    private javax.swing.JTextField fieldJenisHewan;
    private javax.swing.JTextField fieldLayanan;
    private javax.swing.JTextField fieldMetodePembayaran;
    private javax.swing.JTextField fieldNamaHewan;
    private javax.swing.JTextField fieldNamaPemilik;
    private javax.swing.JTextField fieldNoInvoice;
    private javax.swing.JTextField fieldTotalBiaya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
