/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Yoga
 */
public class ViewDaftarHewan extends javax.swing.JFrame {

    /**
     * Creates new form ViewDaftarHewan
     */
    public ViewDaftarHewan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJenisHewan = new javax.swing.JLabel();
        labelUsia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listHewan = new javax.swing.JList<>();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();
        labelJenisKelamin = new javax.swing.JLabel();
        labelPemilik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJenisHewan.setText("Jenis Hewan");

        labelUsia.setText("Usia");
        labelUsia.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelUsia.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelUsia.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jScrollPane1.setViewportView(listHewan);

        btnTambah.setText("Tambah");

        btnHapus.setText("Hapus");

        btnKembali.setText("Kembali");

        labelNama.setText("Nama");

        labelJenisKelamin.setText("Jenis Kelamin");

        labelPemilik.setText("Pemilik");
        labelPemilik.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelPemilik.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelPemilik.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnKembali))
                    .addComponent(labelNama)
                    .addComponent(labelJenisHewan)
                    .addComponent(labelUsia, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJenisKelamin)
                    .addComponent(labelPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKembali)
                            .addComponent(btnTambah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addGap(22, 22, 22)
                        .addComponent(labelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJenisHewan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJenisKelamin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUsia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPemilik))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDaftarHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDaftarHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDaftarHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDaftarHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDaftarHewan().setVisible(true);
            }
        });
    }
    
    public void addActionKembali(ActionListener listener){
        btnKembali.addActionListener(listener);
    }
    
    public void addActionTambahHewanPeliharaan(ActionListener listener){
        btnTambah.addActionListener(listener);
    }
    
    public void addActionHapusHewanPeliharaan(ActionListener listener) {
        btnHapus.addActionListener(listener);
    }
    
    public void DipslayMessage(String S) {
        JOptionPane.showMessageDialog(this, S);
    }
    
    public JList getListHewan() {
        return listHewan;
    }
    
    public void setHewanList(ListModel<String> value) {
        listHewan.setModel(value);
    }
    
    public void setNamaHewan(String nama) {
        labelNama.setText(nama);
    }
    
    public void setNamaPemilik(String namaPemilik) {
        labelPemilik.setText(namaPemilik);
    }
    
    public void setUsiaHewan(String usia) {
        labelUsia.setText(usia);
    }
    
    public void setJenisHewan(String jenisHewan) {
        labelJenisHewan.setText(jenisHewan);
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        labelJenisKelamin.setText(jenisKelamin);
    }
    
    public void addMouseListHewanPeliharaan(MouseAdapter mouse) {
        listHewan.addMouseListener(mouse);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJenisHewan;
    private javax.swing.JLabel labelJenisKelamin;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPemilik;
    private javax.swing.JLabel labelUsia;
    private javax.swing.JList<String> listHewan;
    // End of variables declaration//GEN-END:variables
}
